(cl:defpackage franka_predict_action-srv
  (:use )
  (:export
   "CLEARACTIONQUEUE"
   "<CLEARACTIONQUEUE-REQUEST>"
   "CLEARACTIONQUEUE-REQUEST"
   "<CLEARACTIONQUEUE-RESPONSE>"
   "CLEARACTIONQUEUE-RESPONSE"
   "FETCHSINGLEACTION"
   "<FETCHSINGLEACTION-REQUEST>"
   "FETCHSINGLEACTION-REQUEST"
   "<FETCHSINGLEACTION-RESPONSE>"
   "FETCHSINGLEACTION-RESPONSE"
   "PREDICTACTION"
   "<PREDICTACTION-REQUEST>"
   "PREDICTACTION-REQUEST"
   "<PREDICTACTION-RESPONSE>"
   "PREDICTACTION-RESPONSE"
   "STORENEWACTIONTOQUEUE"
   "<STORENEWACTIONTOQUEUE-REQUEST>"
   "STORENEWACTIONTOQUEUE-REQUEST"
   "<STORENEWACTIONTOQUEUE-RESPONSE>"
   "STORENEWACTIONTOQUEUE-RESPONSE"
  ))

