// Generated by gencpp from file franka_manipulate/MoveitPosCtlRequest.msg
// DO NOT EDIT!


#ifndef FRANKA_MANIPULATE_MESSAGE_MOVEITPOSCTLREQUEST_H
#define FRANKA_MANIPULATE_MESSAGE_MOVEITPOSCTLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_manipulate
{
template <class ContainerAllocator>
struct MoveitPosCtlRequest_
{
  typedef MoveitPosCtlRequest_<ContainerAllocator> Type;

  MoveitPosCtlRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , pitch(0.0)
    , roll(0.0)  {
    }
  MoveitPosCtlRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , pitch(0.0)
    , roll(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _roll_type;
  _roll_type roll;





  typedef boost::shared_ptr< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveitPosCtlRequest_

typedef ::franka_manipulate::MoveitPosCtlRequest_<std::allocator<void> > MoveitPosCtlRequest;

typedef boost::shared_ptr< ::franka_manipulate::MoveitPosCtlRequest > MoveitPosCtlRequestPtr;
typedef boost::shared_ptr< ::franka_manipulate::MoveitPosCtlRequest const> MoveitPosCtlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator1> & lhs, const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator1> & lhs, const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace franka_manipulate

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df92fbb7c3d61a010cb28f0ca4ea7448";
  }

  static const char* value(const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf92fbb7c3d61a01ULL;
  static const uint64_t static_value2 = 0x0cb28f0ca4ea7448ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_manipulate/MoveitPosCtlRequest";
  }

  static const char* value(const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# position in world frame, unit: meter\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"# Euler angles(intrinsic rotation), unit: radian\n"
"float32 yaw    # z axis\n"
"float32 pitch  # y axis\n"
"float32 roll   # x axis\n"
"\n"
;
  }

  static const char* value(const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.pitch);
      stream.next(m.roll);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveitPosCtlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_manipulate::MoveitPosCtlRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_MANIPULATE_MESSAGE_MOVEITPOSCTLREQUEST_H
