// Generated by gencpp from file franka_manipulate/MoveitPosCtl.msg
// DO NOT EDIT!


#ifndef FRANKA_MANIPULATE_MESSAGE_MOVEITPOSCTL_H
#define FRANKA_MANIPULATE_MESSAGE_MOVEITPOSCTL_H

#include <ros/service_traits.h>


#include <franka_manipulate/MoveitPosCtlRequest.h>
#include <franka_manipulate/MoveitPosCtlResponse.h>


namespace franka_manipulate
{

struct MoveitPosCtl
{

typedef MoveitPosCtlRequest Request;
typedef MoveitPosCtlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveitPosCtl
} // namespace franka_manipulate


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_manipulate::MoveitPosCtl > {
  static const char* value()
  {
    return "945ea5a2f427feb9ae87e22a769e0733";
  }

  static const char* value(const ::franka_manipulate::MoveitPosCtl&) { return value(); }
};

template<>
struct DataType< ::franka_manipulate::MoveitPosCtl > {
  static const char* value()
  {
    return "franka_manipulate/MoveitPosCtl";
  }

  static const char* value(const ::franka_manipulate::MoveitPosCtl&) { return value(); }
};


// service_traits::MD5Sum< ::franka_manipulate::MoveitPosCtlRequest> should match
// service_traits::MD5Sum< ::franka_manipulate::MoveitPosCtl >
template<>
struct MD5Sum< ::franka_manipulate::MoveitPosCtlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_manipulate::MoveitPosCtl >::value();
  }
  static const char* value(const ::franka_manipulate::MoveitPosCtlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_manipulate::MoveitPosCtlRequest> should match
// service_traits::DataType< ::franka_manipulate::MoveitPosCtl >
template<>
struct DataType< ::franka_manipulate::MoveitPosCtlRequest>
{
  static const char* value()
  {
    return DataType< ::franka_manipulate::MoveitPosCtl >::value();
  }
  static const char* value(const ::franka_manipulate::MoveitPosCtlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_manipulate::MoveitPosCtlResponse> should match
// service_traits::MD5Sum< ::franka_manipulate::MoveitPosCtl >
template<>
struct MD5Sum< ::franka_manipulate::MoveitPosCtlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_manipulate::MoveitPosCtl >::value();
  }
  static const char* value(const ::franka_manipulate::MoveitPosCtlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_manipulate::MoveitPosCtlResponse> should match
// service_traits::DataType< ::franka_manipulate::MoveitPosCtl >
template<>
struct DataType< ::franka_manipulate::MoveitPosCtlResponse>
{
  static const char* value()
  {
    return DataType< ::franka_manipulate::MoveitPosCtl >::value();
  }
  static const char* value(const ::franka_manipulate::MoveitPosCtlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_MANIPULATE_MESSAGE_MOVEITPOSCTL_H
