controller_manager_ns: controller_manager
controller_list:
  - name: franka_panda/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

  - name: franka_panda/gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - panda_finger_joint1
      - panda_finger_joint2