# position in world frame, unit: meter
float32 x
float32 y
float32 z

# Euler angles(intrinsic rotation), unit: radian
float32 yaw    # z axis
float32 pitch  # y axis
float32 roll   # x axis

---

# result of action
uint8 go_ret