// Generated by gencpp from file franka_predict_action/ClearActionQueue.msg
// DO NOT EDIT!


#ifndef FRANKA_PREDICT_ACTION_MESSAGE_CLEARACTIONQUEUE_H
#define FRANKA_PREDICT_ACTION_MESSAGE_CLEARACTIONQUEUE_H

#include <ros/service_traits.h>


#include <franka_predict_action/ClearActionQueueRequest.h>
#include <franka_predict_action/ClearActionQueueResponse.h>


namespace franka_predict_action
{

struct ClearActionQueue
{

typedef ClearActionQueueRequest Request;
typedef ClearActionQueueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearActionQueue
} // namespace franka_predict_action


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_predict_action::ClearActionQueue > {
  static const char* value()
  {
    return "9d33160d173e7ec57031aac816786381";
  }

  static const char* value(const ::franka_predict_action::ClearActionQueue&) { return value(); }
};

template<>
struct DataType< ::franka_predict_action::ClearActionQueue > {
  static const char* value()
  {
    return "franka_predict_action/ClearActionQueue";
  }

  static const char* value(const ::franka_predict_action::ClearActionQueue&) { return value(); }
};


// service_traits::MD5Sum< ::franka_predict_action::ClearActionQueueRequest> should match
// service_traits::MD5Sum< ::franka_predict_action::ClearActionQueue >
template<>
struct MD5Sum< ::franka_predict_action::ClearActionQueueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_predict_action::ClearActionQueue >::value();
  }
  static const char* value(const ::franka_predict_action::ClearActionQueueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_predict_action::ClearActionQueueRequest> should match
// service_traits::DataType< ::franka_predict_action::ClearActionQueue >
template<>
struct DataType< ::franka_predict_action::ClearActionQueueRequest>
{
  static const char* value()
  {
    return DataType< ::franka_predict_action::ClearActionQueue >::value();
  }
  static const char* value(const ::franka_predict_action::ClearActionQueueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_predict_action::ClearActionQueueResponse> should match
// service_traits::MD5Sum< ::franka_predict_action::ClearActionQueue >
template<>
struct MD5Sum< ::franka_predict_action::ClearActionQueueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_predict_action::ClearActionQueue >::value();
  }
  static const char* value(const ::franka_predict_action::ClearActionQueueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_predict_action::ClearActionQueueResponse> should match
// service_traits::DataType< ::franka_predict_action::ClearActionQueue >
template<>
struct DataType< ::franka_predict_action::ClearActionQueueResponse>
{
  static const char* value()
  {
    return DataType< ::franka_predict_action::ClearActionQueue >::value();
  }
  static const char* value(const ::franka_predict_action::ClearActionQueueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_PREDICT_ACTION_MESSAGE_CLEARACTIONQUEUE_H
