// Generated by gencpp from file franka_predict_action/ClearActionQueueRequest.msg
// DO NOT EDIT!


#ifndef FRANKA_PREDICT_ACTION_MESSAGE_CLEARACTIONQUEUEREQUEST_H
#define FRANKA_PREDICT_ACTION_MESSAGE_CLEARACTIONQUEUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_predict_action
{
template <class ContainerAllocator>
struct ClearActionQueueRequest_
{
  typedef ClearActionQueueRequest_<ContainerAllocator> Type;

  ClearActionQueueRequest_()
    {
    }
  ClearActionQueueRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClearActionQueueRequest_

typedef ::franka_predict_action::ClearActionQueueRequest_<std::allocator<void> > ClearActionQueueRequest;

typedef boost::shared_ptr< ::franka_predict_action::ClearActionQueueRequest > ClearActionQueueRequestPtr;
typedef boost::shared_ptr< ::franka_predict_action::ClearActionQueueRequest const> ClearActionQueueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace franka_predict_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_predict_action/ClearActionQueueRequest";
  }

  static const char* value(const ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearActionQueueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::franka_predict_action::ClearActionQueueRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_PREDICT_ACTION_MESSAGE_CLEARACTIONQUEUEREQUEST_H
