// Generated by gencpp from file franka_predict_action/PredictAction.msg
// DO NOT EDIT!


#ifndef FRANKA_PREDICT_ACTION_MESSAGE_PREDICTACTION_H
#define FRANKA_PREDICT_ACTION_MESSAGE_PREDICTACTION_H

#include <ros/service_traits.h>


#include <franka_predict_action/PredictActionRequest.h>
#include <franka_predict_action/PredictActionResponse.h>


namespace franka_predict_action
{

struct PredictAction
{

typedef PredictActionRequest Request;
typedef PredictActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PredictAction
} // namespace franka_predict_action


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_predict_action::PredictAction > {
  static const char* value()
  {
    return "ae8dd43aecc2d95dbde2901ca04451f5";
  }

  static const char* value(const ::franka_predict_action::PredictAction&) { return value(); }
};

template<>
struct DataType< ::franka_predict_action::PredictAction > {
  static const char* value()
  {
    return "franka_predict_action/PredictAction";
  }

  static const char* value(const ::franka_predict_action::PredictAction&) { return value(); }
};


// service_traits::MD5Sum< ::franka_predict_action::PredictActionRequest> should match
// service_traits::MD5Sum< ::franka_predict_action::PredictAction >
template<>
struct MD5Sum< ::franka_predict_action::PredictActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_predict_action::PredictAction >::value();
  }
  static const char* value(const ::franka_predict_action::PredictActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_predict_action::PredictActionRequest> should match
// service_traits::DataType< ::franka_predict_action::PredictAction >
template<>
struct DataType< ::franka_predict_action::PredictActionRequest>
{
  static const char* value()
  {
    return DataType< ::franka_predict_action::PredictAction >::value();
  }
  static const char* value(const ::franka_predict_action::PredictActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_predict_action::PredictActionResponse> should match
// service_traits::MD5Sum< ::franka_predict_action::PredictAction >
template<>
struct MD5Sum< ::franka_predict_action::PredictActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_predict_action::PredictAction >::value();
  }
  static const char* value(const ::franka_predict_action::PredictActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_predict_action::PredictActionResponse> should match
// service_traits::DataType< ::franka_predict_action::PredictAction >
template<>
struct DataType< ::franka_predict_action::PredictActionResponse>
{
  static const char* value()
  {
    return DataType< ::franka_predict_action::PredictAction >::value();
  }
  static const char* value(const ::franka_predict_action::PredictActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_PREDICT_ACTION_MESSAGE_PREDICTACTION_H
