// Generated by gencpp from file franka_predict_action/StoreNewActionToQueue.msg
// DO NOT EDIT!


#ifndef FRANKA_PREDICT_ACTION_MESSAGE_STORENEWACTIONTOQUEUE_H
#define FRANKA_PREDICT_ACTION_MESSAGE_STORENEWACTIONTOQUEUE_H

#include <ros/service_traits.h>


#include <franka_predict_action/StoreNewActionToQueueRequest.h>
#include <franka_predict_action/StoreNewActionToQueueResponse.h>


namespace franka_predict_action
{

struct StoreNewActionToQueue
{

typedef StoreNewActionToQueueRequest Request;
typedef StoreNewActionToQueueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StoreNewActionToQueue
} // namespace franka_predict_action


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_predict_action::StoreNewActionToQueue > {
  static const char* value()
  {
    return "5b013e147fda06393de0b2e74bcdcf2c";
  }

  static const char* value(const ::franka_predict_action::StoreNewActionToQueue&) { return value(); }
};

template<>
struct DataType< ::franka_predict_action::StoreNewActionToQueue > {
  static const char* value()
  {
    return "franka_predict_action/StoreNewActionToQueue";
  }

  static const char* value(const ::franka_predict_action::StoreNewActionToQueue&) { return value(); }
};


// service_traits::MD5Sum< ::franka_predict_action::StoreNewActionToQueueRequest> should match
// service_traits::MD5Sum< ::franka_predict_action::StoreNewActionToQueue >
template<>
struct MD5Sum< ::franka_predict_action::StoreNewActionToQueueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_predict_action::StoreNewActionToQueue >::value();
  }
  static const char* value(const ::franka_predict_action::StoreNewActionToQueueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_predict_action::StoreNewActionToQueueRequest> should match
// service_traits::DataType< ::franka_predict_action::StoreNewActionToQueue >
template<>
struct DataType< ::franka_predict_action::StoreNewActionToQueueRequest>
{
  static const char* value()
  {
    return DataType< ::franka_predict_action::StoreNewActionToQueue >::value();
  }
  static const char* value(const ::franka_predict_action::StoreNewActionToQueueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_predict_action::StoreNewActionToQueueResponse> should match
// service_traits::MD5Sum< ::franka_predict_action::StoreNewActionToQueue >
template<>
struct MD5Sum< ::franka_predict_action::StoreNewActionToQueueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_predict_action::StoreNewActionToQueue >::value();
  }
  static const char* value(const ::franka_predict_action::StoreNewActionToQueueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_predict_action::StoreNewActionToQueueResponse> should match
// service_traits::DataType< ::franka_predict_action::StoreNewActionToQueue >
template<>
struct DataType< ::franka_predict_action::StoreNewActionToQueueResponse>
{
  static const char* value()
  {
    return DataType< ::franka_predict_action::StoreNewActionToQueue >::value();
  }
  static const char* value(const ::franka_predict_action::StoreNewActionToQueueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_PREDICT_ACTION_MESSAGE_STORENEWACTIONTOQUEUE_H
