(cl:defpackage franka_manipulate-srv
  (:use )
  (:export
   "EXECUSRREQ"
   "<EXECUSRREQ-REQUEST>"
   "EXECUSRREQ-REQUEST"
   "<EXECUSRREQ-RESPONSE>"
   "EXECUSRREQ-RESPONSE"
   "MOVEITPOSCTL"
   "<MOVEITPOSCTL-REQUEST>"
   "MOVEITPOSCTL-REQUEST"
   "<MOVEITPOSCTL-RESPONSE>"
   "MOVEITPOSCTL-RESPONSE"
  ))

